name: Truffle Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup NodeJS ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    
    - name: Clear npm cache
      run: rm -rf node_modules && npm cache clean --force

    - name: Install Truffle Dependencies
      run: npm install

    - name: Install Truffle, TypeScript, @truffle/resolver@9.0.53 ts-node and Ganache
      run: npm install truffle ganache ts-node @truffle/resolver@9.0.53 typescript -g

    - name: Compile TypeScript
      run: npx tsc

    - name: Run Ganache server
      run: npx ganache -p 7545 &

    - name: Run Truffle Test
      run: truffle test
