name: Truffle Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup NodeJS ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install Truffle and Ganache
      run: npm install truffle ganache -g

    - name: Install ts-node globally
      run: npm install ts-node -g

    - name: Install Truffle Dependencies
      run: npm install

    - name: Install TypeScript
      run: npm install typescript --save-dev

    - name: Compile TypeScript
      run: npx tsc

    - name: Run Ganache server
      run: npx ganache -p 7545 &

    - name: Run Truffle Test
      run: truffle test
